### ISSUE TITLE
Strange behavior when "Preferences/Editor/General/Editor Tabs => Open declaration source in the same tab" enabled

### ISSUE THREAD

**Issue by dguendisch** [SeeSharpSoft/intellij-file-preview#29] opened 2019-08-14 11:23 UTC
v1.3.1 wrongly closes an open editor tab (or replaces it with a preview tab).
How to reproduce:
1. Say you have 3 files in your project, double-click on `a.txt` => opens an editor tab for `a.txt`
1. Single-click on `b.txt`: opens a preview for `b.txt` next to `a.txt`
1. In the tab bar click on the tab of `a.txt` => editor tab `a.txt` is now in foreground, preview tab `b.txt` is inactived next to it
1. Single-click on `c.txt` => out of a sudden the editor tab for `a.txt` gets removed and I'm left with a single preview tab for `c.txt`

**Comment by SeeSharpSoft** [comment] 2019-08-14 11:51
After several tries I can't reproduce this behavior. What I noticed sometimes is a slightly confusing tab order change which makes it look like the Editor tab is closed instead of the previous Preview Tab - but actually really the previous Preview Tab was closed but not the "real" Editor Tab.

@dguendisch Can you please re-check whether really `a.txt` is closed or if it is just a tab order change. Thanks!

**Comment by dguendisch** [comment] 2019-08-14 12:00
![2019-08-14_13-56-25 (2)](https://user-images.githubusercontent.com/30311254/63019473-b9ec7300-be9b-11e9-9a8b-577e84eeca6d.gif)

As in the steps to reproduce: my first click on `a.txt` is a double-click, the next clicks are single-clicks.

**Comment by dguendisch** [comment] 2019-08-14 12:11
Maybe even easier: a preview tab that got converted to an editor tab (because of editing), is as well overwritten with the next preview tab. (I hope I didn't got this plugin's functionality wrong, but I was under the impression that preview tabs would never replace editor tabs).

![2019-08-14_14-08-34](https://user-images.githubusercontent.com/30311254/63020050-4cd9dd00-be9d-11e9-9cfd-01d89ac1a8f2.gif)

**Comment by SeeSharpSoft** [comment] 2019-08-14 12:22
I am with you, the shown interactions are unwanted. I still can't reproduce it - for me both cases behave as expected.

It seems from your captures that you have at least "Autoscroll from Source" activated for your Project View, is that right? (I also tried with this option enabled, but it doesn't change anything) Which other Project View options are active? Did you adjust any Quick File Preview settings? Which IDE type/version are you using? Do you have any other plugins installed that might change the editor tab behavior?

**Comment by dguendisch** [comment] 2019-08-14 12:26
Think I found the interfering option: "Preferences/Editor/General/Editor Tabs/Open declaration source in the same tab".
I have that option checked (to prevent this other IntelliJ excessive tab opening :) ).
If I uncheck that option, it works as designed.
Would be cool if intellij-file-preview would work with this option checked as well.

**Comment by SeeSharpSoft** [comment] 2019-08-20 05:58
FYI: This issue is caused by the order of event handlers. To make it work for now, just go to "Preferences/Editor/General/Editor Tabs", deactivate `Open declaration source in the same tab` option and apply, then directly activate it again and apply/OK. That's all!

However, this is just an end-user workaround for short term and works only until the IDE is closed. After each restart the procedure must be repeated. An actual fix is about to be release soon.

**Comment by dguendisch** [comment] 2019-08-25 16:36
> An actual fix is about to be released soon.

Is that supposed to be fixed in v1.4.3?
While I cannot reproduce this issue anymore reliably, I still occasionally run into preview tabs "eating" editor tabs (that is, "overwriting" an open editor tab with a preview one upon clicking in the project view).

**Comment by SeeSharpSoft** [comment] 2019-08-26 06:53
Gets automatically closed due to commit message - lets keep it open until fix confirmed in release 1.4.5

**Comment by dguendisch** [comment] 2019-08-26 12:16
With 1.4.5 I see another "eating" behaviour (reproducible):
- Double click a file to have one open editor tab
- Single click a file to have an additional preview tab
- Manually close the preview tab by hitting the `X` on the tab itself => leaves one open editor tab
- Single click another file => it overwrites my open editor tab and replaces it with a preview one

**Comment by SeeSharpSoft** [comment] 2019-08-27 07:16
Thanks, I am really appreciating your validation! It's all about having the focus right - still working on it...

**Comment by dguendisch** [comment] 2019-08-30 12:35
Just noticed a new 1.4.6 version. On a first look I couldn't reproduce any "eating" issue anymore, thanks!

**Comment by SeeSharpSoft** [comment] 2019-09-09 05:41
After some time of usage now I also couldn't find any further hiccups regarding this interactions - closing it for now.

**Closed by SeeSharpSoft** 2019-09-09 05:41 UTC
Labels: bug, in development
